/**
 * The word list of DATEX-022 Random - Passphrase: 1338 common English words of 3 to 8 lower-case
 * ASCII letters, without repeats, sorted. The list was written for this extension (it is not a copy
 * of another word list), so it has no license of its own beyond the extension's. With 1338 words
 * one word gives log2(1338) ≈ 10.4 bits; the default of 6 words gives about 62 bits.
 */
export const PASSPHRASE_WORDS: readonly string[] = [
  'able', 'acorn', 'acre', 'actor', 'adapt', 'adobe', 'aerial', 'agent', 'agile', 'aisle', 'alarm', 'album',
  'alert', 'alley', 'almond', 'alpaca', 'alpine', 'amber', 'amount', 'amulet', 'anchor', 'angel', 'angle',
  'ankle', 'answer', 'apple', 'apricot', 'april', 'apron', 'aqua', 'arbor', 'arcade', 'arch', 'ardent',
  'arena', 'armchair', 'armor', 'aroma', 'arrow', 'artist', 'ascent', 'aspect', 'aspen', 'atlas', 'atom',
  'attic', 'attire', 'audio', 'august', 'autumn', 'avenue', 'avocado', 'awake', 'award', 'axis', 'baboon',
  'bacon', 'badge', 'badger', 'bagel', 'baker', 'bakery', 'balance', 'ballad', 'ballet', 'balloon', 'bamboo',
  'banana', 'band', 'bandana', 'bangle', 'banjo', 'banner', 'banquet', 'barley', 'barn', 'baron', 'barrel',
  'basalt', 'basil', 'basin', 'basket', 'batch', 'bayou', 'bazaar', 'beach', 'beacon', 'beagle', 'beam',
  'bean', 'beard', 'beaver', 'bedroom', 'beech', 'beetle', 'bell', 'belt', 'bench', 'beret', 'berry',
  'bicycle', 'binder', 'birch', 'bird', 'biscuit', 'bishop', 'bison', 'blade', 'blanket', 'blaze', 'blend',
  'blender', 'blimp', 'blink', 'block', 'bloom', 'blossom', 'blue', 'bluff', 'blush', 'board', 'boat',
  'bobcat', 'bolt', 'bongo', 'bonnet', 'bonus', 'book', 'boot', 'border', 'bottle', 'boulder', 'bounce',
  'bounty', 'bowl', 'boxer', 'bracket', 'brain', 'branch', 'brave', 'bread', 'breadth', 'breeze', 'brick',
  'bridge', 'brief', 'bright', 'brine', 'bronze', 'brook', 'broom', 'brush', 'bubble', 'bucket', 'buckle',
  'budget', 'buffalo', 'bugle', 'bugler', 'bundle', 'bunny', 'burger', 'burrow', 'bushel', 'butter',
  'button', 'buzzer', 'cabbage', 'cabin', 'cable', 'cactus', 'caddie', 'calico', 'camel', 'camera', 'camp',
  'camper', 'canal', 'candle', 'candor', 'candy', 'cannon', 'canoe', 'canvas', 'canyon', 'cape', 'caramel',
  'caravan', 'carbon', 'card', 'cardinal', 'cargo', 'carpet', 'carrot', 'cart', 'cashew', 'castle',
  'catalog', 'cattle', 'caviar', 'cedar', 'celery', 'cellar', 'cello', 'cement', 'census', 'cereal', 'chain',
  'chair', 'chalk', 'channel', 'chapel', 'chapter', 'chariot', 'charm', 'chart', 'cheese', 'cheetah',
  'cherry', 'chess', 'chest', 'chicken', 'chili', 'chimes', 'chimney', 'chipmunk', 'chorus', 'chowder',
  'cider', 'cinema', 'cinnamon', 'circle', 'circus', 'citadel', 'citrus', 'city', 'clarinet', 'clay',
  'clerk', 'cliff', 'climb', 'clipper', 'clock', 'cloud', 'clover', 'coach', 'coast', 'cobalt', 'cobbler',
  'cockatoo', 'cocoa', 'coconut', 'coffee', 'coin', 'collar', 'comet', 'comfort', 'compass', 'condor',
  'cookbook', 'cookie', 'copper', 'coral', 'corner', 'coronet', 'corridor', 'cottage', 'cotton', 'couch',
  'cougar', 'county', 'course', 'cousin', 'cove', 'cowboy', 'coyote', 'crab', 'cradle', 'crane', 'crater',
  'crayon', 'cream', 'credit', 'crescent', 'crest', 'cricket', 'crocus', 'crown', 'crumpet', 'crystal',
  'cube', 'cuckoo', 'cup', 'cupboard', 'curtain', 'cushion', 'custard', 'cycle', 'cymbal', 'dahlia', 'daisy',
  'dance', 'dancer', 'dapper', 'darling', 'datum', 'dawn', 'debut', 'decade', 'deck', 'decoy', 'delta',
  'deluxe', 'denim', 'dentist', 'depot', 'derby', 'desert', 'design', 'desk', 'dessert', 'detail', 'dew',
  'dial', 'diamond', 'diary', 'dimple', 'dinghy', 'dingo', 'dinner', 'diploma', 'dish', 'ditto', 'dock',
  'doctor', 'dollar', 'dolphin', 'domain', 'domino', 'donkey', 'donut', 'doodle', 'door', 'dormouse', 'dove',
  'dozen', 'dragon', 'drawer', 'dream', 'dress', 'drift', 'drizzle', 'drum', 'duck', 'duet', 'dumpling',
  'dune', 'dusk', 'dust', 'eagle', 'earring', 'easel', 'easter', 'echo', 'eclipse', 'edge', 'editor',
  'eggplant', 'eight', 'elbow', 'elder', 'elegant', 'elephant', 'elevator', 'elixir', 'elk', 'elm',
  'embassy', 'ember', 'emblem', 'emerald', 'empire', 'enamel', 'endive', 'engine', 'enigma', 'envoy',
  'equal', 'equator', 'erase', 'errand', 'escape', 'essay', 'estate', 'eureka', 'evening', 'event', 'exact',
  'exhibit', 'exit', 'expert', 'fable', 'fabric', 'falafel', 'falcon', 'family', 'fancy', 'fanfare', 'farm',
  'fawn', 'feast', 'feather', 'fence', 'fennel', 'ferry', 'fiddle', 'field', 'fiesta', 'fig', 'figure',
  'filament', 'filter', 'finch', 'fire', 'fireside', 'fixture', 'fjord', 'flag', 'flame', 'flannel', 'flash',
  'fleet', 'flicker', 'flint', 'flipper', 'flock', 'floor', 'florist', 'flour', 'flower', 'flute', 'foal',
  'focus', 'fog', 'folder', 'fondue', 'footpath', 'forest', 'forge', 'fork', 'fossil', 'fountain', 'fox',
  'frame', 'freckle', 'fresco', 'fresh', 'friday', 'fridge', 'frigate', 'fritter', 'frolic', 'frost',
  'fruit', 'fudge', 'funnel', 'furnace', 'gadget', 'galaxy', 'galleon', 'gallery', 'gallon', 'game',
  'gander', 'garage', 'garden', 'garland', 'garlic', 'garnet', 'gate', 'gauge', 'gazebo', 'gazelle', 'gecko',
  'gelato', 'gem', 'gentle', 'geyser', 'gherkin', 'giant', 'ginger', 'giraffe', 'glacier', 'glade', 'glass',
  'glider', 'globe', 'glove', 'glow', 'gnome', 'goblet', 'goblin', 'gold', 'goldfish', 'golf', 'gondola',
  'goose', 'gopher', 'gorilla', 'gourd', 'gourmet', 'grain', 'granite', 'granola', 'grape', 'graph', 'grass',
  'gravel', 'gravy', 'green', 'gremlin', 'grid', 'griddle', 'grizzly', 'grove', 'guitar', 'gull', 'gumdrop',
  'guppy', 'gusto', 'habit', 'hacienda', 'haddock', 'halibut', 'hallway', 'halo', 'hammer', 'hammock',
  'hamster', 'hand', 'hangar', 'harbor', 'harmony', 'harp', 'harvest', 'hatch', 'hatchet', 'haven', 'hawk',
  'haystack', 'hazel', 'heart', 'hedge', 'helmet', 'hemlock', 'herb', 'hermit', 'heron', 'hickory', 'hiking',
  'hill', 'hippo', 'hobby', 'hockey', 'holly', 'homework', 'honey', 'honeybee', 'hood', 'hook', 'horizon',
  'hornet', 'horse', 'hostel', 'hotel', 'hound', 'house', 'humble', 'hummus', 'hurdle', 'husky', 'hut',
  'hyacinth', 'ibis', 'iceberg', 'icecap', 'icicle', 'icon', 'idea', 'igloo', 'illusion', 'impala',
  'incense', 'inch', 'index', 'indigo', 'infant', 'ink', 'inkwell', 'inlet', 'insect', 'inventor', 'iris',
  'island', 'italic', 'ivory', 'ivy', 'jackal', 'jacket', 'jaguar', 'jam', 'jar', 'jasmine', 'jaunty',
  'javelin', 'jelly', 'jersey', 'jester', 'jetty', 'jewel', 'jigsaw', 'jingle', 'jockey', 'jogger',
  'journal', 'journey', 'joy', 'jubilee', 'judge', 'juice', 'jukebox', 'july', 'jumbo', 'junction', 'jungle',
  'juniper', 'jupiter', 'jury', 'kale', 'kangaroo', 'karate', 'kayak', 'keepsake', 'kelp', 'kennel',
  'kernel', 'kestrel', 'kettle', 'key', 'keyboard', 'kimono', 'kingdom', 'kinship', 'kiosk', 'kipper',
  'kitchen', 'kite', 'kitten', 'kiwi', 'knapsack', 'knee', 'knight', 'knot', 'koala', 'label', 'lacquer',
  'ladder', 'ladle', 'lagoon', 'lake', 'lamb', 'lamp', 'lantern', 'lanyard', 'laptop', 'large', 'lark',
  'lasagna', 'latch', 'lattice', 'laurel', 'lava', 'lavender', 'lawn', 'layer', 'leaf', 'ledge', 'legend',
  'legume', 'lemon', 'lemonade', 'lens', 'leopard', 'letter', 'lettuce', 'level', 'lever', 'library',
  'lichen', 'lilac', 'lily', 'lime', 'limerick', 'linen', 'linnet', 'lion', 'liquid', 'list', 'lizard',
  'llama', 'lobby', 'lobster', 'locket', 'lodge', 'lollipop', 'lotus', 'lucky', 'lumber', 'lunar', 'lunch',
  'lute', 'macaw', 'machine', 'mackerel', 'madrigal', 'magician', 'magnet', 'magpie', 'maize', 'mallard',
  'mammoth', 'mandolin', 'mango', 'manor', 'mantis', 'maple', 'marble', 'march', 'marina', 'market',
  'marlin', 'marmot', 'marrow', 'marsh', 'mascot', 'mason', 'meadow', 'medal', 'meerkat', 'melody', 'melon',
  'memory', 'menthol', 'mercury', 'meringue', 'mermaid', 'meteor', 'method', 'metro', 'middle', 'mild',
  'mill', 'mimosa', 'mineral', 'minnow', 'minute', 'mirror', 'mistral', 'mitten', 'moccasin', 'model',
  'modest', 'mohair', 'molasses', 'moment', 'monday', 'mongoose', 'monkey', 'monsoon', 'moon', 'moose',
  'morning', 'morsel', 'mosaic', 'moss', 'motor', 'mountain', 'mouse', 'muesli', 'muffin', 'mulberry',
  'mural', 'museum', 'music', 'mussel', 'mustard', 'mystic', 'nacho', 'napkin', 'narrow', 'native', 'nature',
  'nautilus', 'navy', 'nebula', 'nectar', 'needle', 'nephew', 'nest', 'nettle', 'network', 'newt', 'nickel',
  'night', 'nimble', 'noble', 'nomad', 'noodle', 'north', 'notebook', 'nougat', 'novel', 'nugget', 'number',
  'nursery', 'nutmeg', 'oasis', 'oatmeal', 'oboe', 'ocean', 'octagon', 'october', 'octopus', 'odyssey',
  'office', 'olive', 'omega', 'omelet', 'onion', 'opal', 'opera', 'opossum', 'oracle', 'orange', 'orbit',
  'orchard', 'orchid', 'organ', 'osprey', 'ostrich', 'otter', 'outlet', 'outpost', 'oval', 'oven',
  'overture', 'owl', 'oxygen', 'oyster', 'paddle', 'page', 'pagoda', 'paint', 'paisley', 'palace', 'palette',
  'palm', 'pancake', 'panda', 'panel', 'panther', 'pantry', 'papaya', 'paper', 'paprika', 'parade',
  'parasol', 'parcel', 'parrot', 'parsley', 'partner', 'passport', 'pasta', 'pastel', 'pastry', 'patio',
  'pattern', 'paver', 'peach', 'peacock', 'peanut', 'pear', 'pebble', 'pedal', 'pelican', 'pencil',
  'penguin', 'pennant', 'peony', 'pepper', 'percent', 'petal', 'pheasant', 'piano', 'pickle', 'picnic',
  'pigeon', 'pilgrim', 'pillow', 'pilot', 'pine', 'pinecone', 'pinwheel', 'pioneer', 'pirate', 'piston',
  'pizza', 'placid', 'planet', 'plank', 'platypus', 'plaza', 'pleat', 'plover', 'plum', 'plume', 'plywood',
  'pocket', 'poem', 'polar', 'polka', 'pomelo', 'pond', 'pony', 'poodle', 'popcorn', 'poppy', 'porch',
  'porridge', 'portal', 'possum', 'postcard', 'potato', 'pottery', 'poultry', 'powder', 'prairie', 'praline',
  'prawn', 'pretzel', 'primrose', 'prism', 'pudding', 'puffin', 'pulsar', 'pumpkin', 'puppet', 'puzzle',
  'pyramid', 'quail', 'quaint', 'quarter', 'quartz', 'quasar', 'queen', 'quench', 'quest', 'quick', 'quiet',
  'quill', 'quilt', 'quiver', 'quokka', 'quota', 'rabbit', 'raccoon', 'radar', 'radiant', 'radio', 'radish',
  'raft', 'ragtime', 'rail', 'rainbow', 'raisin', 'rampart', 'ranch', 'range', 'rapids', 'raven', 'ravioli',
  'razor', 'recital', 'reef', 'reindeer', 'relay', 'relish', 'remedy', 'remote', 'reptile', 'resin',
  'retreat', 'rhubarb', 'rhythm', 'ribbon', 'rice', 'ricotta', 'riddle', 'ridge', 'ring', 'river',
  'riverbed', 'road', 'roadway', 'robin', 'robot', 'rocket', 'rodeo', 'roof', 'rookie', 'rose', 'rosemary',
  'route', 'rover', 'rowboat', 'rubble', 'ruby', 'rudder', 'ruffle', 'rug', 'ruler', 'rustic', 'sable',
  'sachet', 'saddle', 'safari', 'saffron', 'sail', 'salad', 'salmon', 'salsa', 'salt', 'sample', 'sand',
  'sandal', 'sapphire', 'sardine', 'sashimi', 'satchel', 'satin', 'saturn', 'sauce', 'saucer', 'savanna',
  'scallop', 'scarf', 'scepter', 'school', 'scone', 'scooter', 'scout', 'screen', 'sculptor', 'seagull',
  'seashell', 'season', 'seed', 'sequoia', 'shadow', 'shark', 'shelf', 'shell', 'sherbet', 'shield', 'ship',
  'shore', 'shovel', 'shrimp', 'shrub', 'signal', 'silk', 'silver', 'singer', 'siren', 'skate', 'sketch',
  'ski', 'sky', 'skylark', 'slalom', 'slate', 'sled', 'sleigh', 'slipper', 'slogan', 'smile', 'smoothie',
  'snack', 'snail', 'snorkel', 'snow', 'soap', 'soccer', 'sock', 'sofa', 'solar', 'sonnet', 'sorbet', 'soup',
  'soybean', 'spark', 'sparrow', 'spatula', 'sphinx', 'spice', 'spider', 'spinach', 'spindle', 'sponge',
  'spoon', 'spring', 'sprout', 'square', 'squash', 'squid', 'stable', 'stage', 'stairs', 'stallion', 'stamp',
  'star', 'starfish', 'statue', 'steam', 'stencil', 'stingray', 'stone', 'stool', 'storm', 'story', 'stove',
  'straw', 'stream', 'street', 'strudel', 'studio', 'sugar', 'summer', 'summit', 'sunday', 'sundial',
  'sunset', 'swallow', 'swan', 'sweater', 'swift', 'sycamore', 'symbol', 'table', 'tablet', 'taco',
  'tadpole', 'taffy', 'tailor', 'talent', 'tamarind', 'tambour', 'tandem', 'tango', 'tape', 'tapestry',
  'tapioca', 'target', 'tavern', 'teacup', 'teapot', 'temple', 'tennis', 'tent', 'terrace', 'thicket',
  'thimble', 'thistle', 'thread', 'thunder', 'thyme', 'ticket', 'tiger', 'timber', 'timpani', 'tinsel',
  'toast', 'today', 'toffee', 'token', 'tomato', 'topaz', 'topiary', 'torch', 'tortoise', 'toucan', 'towel',
  'tower', 'tractor', 'trail', 'train', 'treaty', 'tree', 'trellis', 'tribe', 'trident', 'trinket',
  'trolley', 'trophy', 'trout', 'truck', 'trumpet', 'tugboat', 'tulip', 'tundra', 'tunnel', 'turkey',
  'turnip', 'turtle', 'tuxedo', 'twig', 'twilight', 'ukulele', 'ultra', 'umbrella', 'uncle', 'unicorn',
  'union', 'unison', 'unit', 'upbeat', 'uplift', 'upper', 'urban', 'useful', 'utensil', 'utmost', 'vacuum',
  'valiant', 'valley', 'valve', 'vanguard', 'vanilla', 'vapor', 'varnish', 'vase', 'vaulted', 'velvet',
  'venue', 'verdant', 'verse', 'vertex', 'vessel', 'vest', 'viaduct', 'village', 'vine', 'vintage', 'viola',
  'violet', 'violin', 'vireo', 'visit', 'vista', 'vivid', 'voice', 'volcano', 'vortex', 'voyage', 'wafer',
  'waffle', 'wagon', 'waiter', 'walkway', 'walnut', 'walrus', 'wand', 'warbler', 'warm', 'wasabi',
  'waterway', 'wave', 'wealth', 'weasel', 'weaver', 'weekend', 'whale', 'wharf', 'wheat', 'wheel', 'whisker',
  'whistle', 'wicker', 'wildcat', 'willow', 'windmill', 'window', 'wingspan', 'winter', 'wisteria', 'wizard',
  'wolf', 'wombat', 'wonder', 'woodland', 'wool', 'worker', 'wren', 'yacht', 'yak', 'yard', 'yarn', 'year',
  'yearbook', 'yellow', 'yeoman', 'yodel', 'yogurt', 'yolk', 'yonder', 'young', 'zealous', 'zebra', 'zenith',
  'zephyr', 'zero', 'zigzag', 'zinc', 'zinnia', 'zipper', 'zodiac', 'zone', 'zucchini',
];
