/**
 * Hash and checksum algorithms implemented in plain TypeScript (HASH-003..004, 006..007, 010..013,
 * and ENCX-016..020 of group ENC2).
 *
 * VS Code's extension host runs on Electron, whose `node:crypto` is backed by BoringSSL and does
 * not support SHA-3, BLAKE2 or HMAC-SHA3 (`Digest method not supported` / `Invalid digest`), even
 * though the Node.js CLI (OpenSSL) does. These algorithms are therefore implemented here, without
 * any dependency, so that the result never depends on the runtime:
 *
 * - SHA3-256 / SHA3-384 / SHA3-512 and SHAKE256 (FIPS 202, Keccak-f[1600])
 * - BLAKE2b-512 / BLAKE2s-256 (RFC 7693, unkeyed)
 * - HMAC (RFC 2104) over any of the above, HMAC-SHA3-256 (block size 136 bytes) and
 *   HMAC-SHA3-512 (block size 72 bytes)
 * - CRC-32 (IEEE 802.3), CRC-32C (Castagnoli), CRC-16/CCITT-FALSE, Adler-32 and FNV-1a 32-bit
 *   (error detection only, not tamper-proof)
 *
 * 64-bit words are handled as pairs of unsigned 32-bit integers (low word first) instead of
 * `BigInt`, which is much slower. Every function is O(n) in the input length and reuses its work
 * arrays across blocks. These functions only compute digests; they are not constant-time and are
 * not meant for comparing secrets.
 */

// ---------------------------------------------------------------------------
// SHA-3 (FIPS 202)
// ---------------------------------------------------------------------------

/** The 24 round constants of Keccak-f[1600] as [low, high] pairs, generated by the FIPS 202 LFSR (rc(t)). */
const KECCAK_ROUND_CONSTANTS = ((): Uint32Array => {
  const constants = new Uint32Array(48);
  let r = 1;
  for (let round = 0; round < 24; round++) {
    let lo = 0;
    let hi = 0;
    for (let j = 0; j < 7; j++) {
      // x^8 + x^6 + x^5 + x^4 + 1
      r = ((r << 1) ^ ((r >> 7) * 0x71)) & 0xff;
      if (r & 2) {
        const bit = (1 << j) - 1;
        if (bit < 32) {
          lo |= 1 << bit;
        } else {
          hi |= 1 << (bit - 32);
        }
      }
    }
    constants[2 * round] = lo;
    constants[2 * round + 1] = hi;
  }
  return constants;
})();

/**
 * ρ rotation offsets and π destinations per lane (lane index = x + 5y), derived as in FIPS 202
 * 3.2.2 / 3.2.3: the offsets follow (x, y) ← (y, 2x + 3y) starting at (1, 0), and π moves lane
 * (x, y) to (y, 2x + 3y).
 */
const KECCAK_RHO = new Uint8Array(25);
const KECCAK_PI = new Uint8Array(25);
(() => {
  let x = 1;
  let y = 0;
  for (let t = 0; t < 24; t++) {
    KECCAK_RHO[x + 5 * y] = (((t + 1) * (t + 2)) / 2) % 64;
    [x, y] = [y, (2 * x + 3 * y) % 5];
  }
  for (let lx = 0; lx < 5; lx++) {
    for (let ly = 0; ly < 5; ly++) {
      KECCAK_PI[lx + 5 * ly] = ly + 5 * ((2 * lx + 3 * ly) % 5);
    }
  }
})();

/** Keccak-f[1600] on `state` (25 lanes as 50 words, low word first); `b` and `c` are work arrays. */
const keccakF = (state: Uint32Array, b: Uint32Array, c: Uint32Array): void => {
  for (let round = 0; round < 24; round++) {
    // θ
    for (let x = 0; x < 5; x++) {
      c[2 * x] = state[2 * x] ^ state[2 * x + 10] ^ state[2 * x + 20] ^ state[2 * x + 30] ^ state[2 * x + 40];
      c[2 * x + 1] = state[2 * x + 1] ^ state[2 * x + 11] ^ state[2 * x + 21] ^ state[2 * x + 31] ^ state[2 * x + 41];
    }
    for (let x = 0; x < 5; x++) {
      const p = 2 * ((x + 4) % 5);
      const n = 2 * ((x + 1) % 5);
      // D[x] = C[x - 1] ^ rotl(C[x + 1], 1)
      const dlo = c[p] ^ ((c[n] << 1) | (c[n + 1] >>> 31));
      const dhi = c[p + 1] ^ ((c[n + 1] << 1) | (c[n] >>> 31));
      for (let y = 0; y < 25; y += 5) {
        state[2 * (x + y)] ^= dlo;
        state[2 * (x + y) + 1] ^= dhi;
      }
    }
    // ρ and π
    for (let i = 0; i < 25; i++) {
      const lo = state[2 * i];
      const hi = state[2 * i + 1];
      const shift = KECCAK_RHO[i];
      const d = 2 * KECCAK_PI[i];
      if (shift === 0) {
        b[d] = lo;
        b[d + 1] = hi;
      } else if (shift < 32) {
        b[d] = (lo << shift) | (hi >>> (32 - shift));
        b[d + 1] = (hi << shift) | (lo >>> (32 - shift));
      } else if (shift === 32) {
        b[d] = hi;
        b[d + 1] = lo;
      } else {
        const m = shift - 32;
        b[d] = (hi << m) | (lo >>> (32 - m));
        b[d + 1] = (lo << m) | (hi >>> (32 - m));
      }
    }
    // χ
    for (let y = 0; y < 25; y += 5) {
      for (let x = 0; x < 5; x++) {
        const i = 2 * (x + y);
        const i1 = 2 * (((x + 1) % 5) + y);
        const i2 = 2 * (((x + 2) % 5) + y);
        state[i] = b[i] ^ (~b[i1] & b[i2]);
        state[i + 1] = b[i + 1] ^ (~b[i1 + 1] & b[i2 + 1]);
      }
    }
    // ι
    state[0] ^= KECCAK_ROUND_CONSTANTS[2 * round];
    state[1] ^= KECCAK_ROUND_CONSTANTS[2 * round + 1];
  }
};

/** Reads 4 bytes at `offset` as a little-endian unsigned 32-bit integer. */
const readUint32LE = (bytes: Uint8Array, offset: number): number =>
  (bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16) | (bytes[offset + 3] << 24)) >>> 0;

/** Writes the first `length` bytes of `words` (little-endian) to a new array. */
const wordsToBytesLE = (words: Uint32Array, length: number): Uint8Array => {
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i++) {
    out[i] = (words[i >>> 2] >>> (8 * (i & 3))) & 0xff;
  }
  return out;
};

/** The domain separation suffix of the SHA-3 hash functions (FIPS 202 6.1). */
const SHA3_SUFFIX = 0x06;
/** The domain separation suffix of the SHAKE extendable-output functions (FIPS 202 6.2). */
const SHAKE_SUFFIX = 0x1f;

/**
 * The Keccak[c] sponge with the given rate in bytes and domain separation suffix, squeezed to
 * `outputLength` bytes (any length: one more permutation per further block of `rate` bytes).
 */
const keccakSponge = (rate: number, suffix: number, outputLength: number, bytes: Uint8Array): Uint8Array => {
  const state = new Uint32Array(50);
  const b = new Uint32Array(50);
  const c = new Uint32Array(10);
  const words = rate / 4;
  const absorb = (block: Uint8Array, offset: number) => {
    for (let i = 0; i < words; i++) {
      state[i] ^= readUint32LE(block, offset + 4 * i);
    }
    keccakF(state, b, c);
  };
  let offset = 0;
  for (; bytes.length - offset >= rate; offset += rate) {
    absorb(bytes, offset);
  }
  // The last (possibly empty) partial block with the suffix and the pad10*1 padding; the suffix
  // and 0x80 are combined when they fall on the same byte (0x86 for SHA-3, 0x9F for SHAKE).
  const last = new Uint8Array(rate);
  last.set(bytes.subarray(offset));
  last[bytes.length - offset] ^= suffix;
  last[rate - 1] ^= 0x80;
  absorb(last, 0);
  if (outputLength <= rate) {
    return wordsToBytesLE(state, outputLength);
  }
  const out = new Uint8Array(outputLength);
  for (let written = 0; written < outputLength; written += rate) {
    if (written > 0) {
      keccakF(state, b, c);
    }
    out.set(wordsToBytesLE(state, Math.min(rate, outputLength - written)), written);
  }
  return out;
};

/** SHA3-256 (rate 136 bytes). */
export const sha3_256 = (bytes: Uint8Array): Uint8Array => keccakSponge(136, SHA3_SUFFIX, 32, bytes);
/** SHA3-384 (rate 104 bytes). */
export const sha3_384 = (bytes: Uint8Array): Uint8Array => keccakSponge(104, SHA3_SUFFIX, 48, bytes);
/** SHA3-512 (rate 72 bytes). */
export const sha3_512 = (bytes: Uint8Array): Uint8Array => keccakSponge(72, SHA3_SUFFIX, 64, bytes);
/** SHAKE256 (rate 136 bytes) with an output of `outputLength` bytes (a non-negative integer). */
export const shake256 = (bytes: Uint8Array, outputLength: number): Uint8Array => {
  if (!Number.isSafeInteger(outputLength) || outputLength < 0) {
    throw new RangeError('the SHAKE256 output length must be a non-negative integer');
  }
  return keccakSponge(136, SHAKE_SUFFIX, outputLength, bytes);
};
/** The block size (rate) of SHA3-256 in bytes, used as the HMAC block size. */
export const SHA3_256_BLOCK_SIZE = 136;
/** The block size (rate) of SHA3-512 in bytes, used as the HMAC block size. */
export const SHA3_512_BLOCK_SIZE = 72;

// ---------------------------------------------------------------------------
// BLAKE2 (RFC 7693)
// ---------------------------------------------------------------------------

/** The message word permutations σ[0..9] of BLAKE2. */
const BLAKE2_SIGMA: readonly (readonly number[])[] = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
  [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
  [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
  [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
  [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
  [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
  [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
  [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
  [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
];

/** The BLAKE2b IV (the SHA-512 IV) as [low, high] pairs. */
const BLAKE2B_IV = new Uint32Array([
  0xf3bcc908, 0x6a09e667, 0x84caa73b, 0xbb67ae85, 0xfe94f82b, 0x3c6ef372, 0x5f1d36f1, 0xa54ff53a,
  0xade682d1, 0x510e527f, 0x2b3e6c1f, 0x9b05688c, 0xfb41bd6b, 0x1f83d9ab, 0x137e2179, 0x5be0cd19,
]);

/** The BLAKE2s IV (the SHA-256 IV). */
const BLAKE2S_IV = new Uint32Array([
  0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
]);

const TWO_POW_32 = 0x100000000;

/**
 * Runs the BLAKE2 block structure shared by BLAKE2b and BLAKE2s: every block but the last is
 * compressed with the byte counter so far, the last block (zero-padded; one all-zero block for an
 * empty input) with the final flag.
 */
const blake2Blocks = (
  bytes: Uint8Array,
  blockSize: number,
  compress: (block: Uint8Array, offset: number, counter: number, last: boolean) => void
): void => {
  let offset = 0;
  for (; bytes.length - offset > blockSize; offset += blockSize) {
    compress(bytes, offset, offset + blockSize, false);
  }
  const last = new Uint8Array(blockSize);
  last.set(bytes.subarray(offset));
  compress(last, 0, bytes.length, true);
};

/** BLAKE2b with a 64-byte digest and no key (parameter block 0x01010040). */
export const blake2b512 = (bytes: Uint8Array): Uint8Array => {
  const h = new Uint32Array(BLAKE2B_IV);
  h[0] ^= 0x01010040;
  const v = new Uint32Array(32);
  const m = new Uint32Array(32);

  /** v[a] += v[b] (64-bit, word indices). */
  const add = (a: number, b: number) => {
    const lo = v[a] + v[b];
    v[a + 1] = v[a + 1] + v[b + 1] + (lo >= TWO_POW_32 ? 1 : 0);
    v[a] = lo;
  };
  /** v[a] += m[i] (64-bit, word indices). */
  const addMessage = (a: number, i: number) => {
    const lo = v[a] + m[i];
    v[a + 1] = v[a + 1] + m[i + 1] + (lo >= TWO_POW_32 ? 1 : 0);
    v[a] = lo;
  };
  const g = (a: number, b: number, c: number, d: number, x: number, y: number) => {
    addMessage(a, x);
    add(a, b);
    // d = rotr64(d ^ a, 32)
    let lo = v[d] ^ v[a];
    let hi = v[d + 1] ^ v[a + 1];
    v[d] = hi;
    v[d + 1] = lo;
    add(c, d);
    // b = rotr64(b ^ c, 24)
    lo = v[b] ^ v[c];
    hi = v[b + 1] ^ v[c + 1];
    v[b] = (lo >>> 24) | (hi << 8);
    v[b + 1] = (hi >>> 24) | (lo << 8);
    addMessage(a, y);
    add(a, b);
    // d = rotr64(d ^ a, 16)
    lo = v[d] ^ v[a];
    hi = v[d + 1] ^ v[a + 1];
    v[d] = (lo >>> 16) | (hi << 16);
    v[d + 1] = (hi >>> 16) | (lo << 16);
    add(c, d);
    // b = rotr64(b ^ c, 63)
    lo = v[b] ^ v[c];
    hi = v[b + 1] ^ v[c + 1];
    v[b] = (hi >>> 31) | (lo << 1);
    v[b + 1] = (lo >>> 31) | (hi << 1);
  };

  blake2Blocks(bytes, 128, (block, offset, counter, last) => {
    for (let i = 0; i < 16; i++) {
      v[i] = h[i];
      v[i + 16] = BLAKE2B_IV[i];
    }
    // The 128-bit counter: inputs never reach 2^53 bytes, so its upper 64 bits stay zero.
    v[24] ^= counter % TWO_POW_32;
    v[25] ^= Math.floor(counter / TWO_POW_32);
    if (last) {
      v[28] = ~v[28];
      v[29] = ~v[29];
    }
    for (let i = 0; i < 32; i++) {
      m[i] = readUint32LE(block, offset + 4 * i);
    }
    for (let round = 0; round < 12; round++) {
      const s = BLAKE2_SIGMA[round % 10];
      g(0, 8, 16, 24, 2 * s[0], 2 * s[1]);
      g(2, 10, 18, 26, 2 * s[2], 2 * s[3]);
      g(4, 12, 20, 28, 2 * s[4], 2 * s[5]);
      g(6, 14, 22, 30, 2 * s[6], 2 * s[7]);
      g(0, 10, 20, 30, 2 * s[8], 2 * s[9]);
      g(2, 12, 22, 24, 2 * s[10], 2 * s[11]);
      g(4, 14, 16, 26, 2 * s[12], 2 * s[13]);
      g(6, 8, 18, 28, 2 * s[14], 2 * s[15]);
    }
    for (let i = 0; i < 16; i++) {
      h[i] ^= v[i] ^ v[i + 16];
    }
  });
  return wordsToBytesLE(h, 64);
};

/** BLAKE2s with a 32-byte digest and no key (parameter block 0x01010020). */
export const blake2s256 = (bytes: Uint8Array): Uint8Array => {
  const h = new Uint32Array(BLAKE2S_IV);
  h[0] ^= 0x01010020;
  const v = new Uint32Array(16);
  const m = new Uint32Array(16);
  const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n));
  const g = (a: number, b: number, c: number, d: number, x: number, y: number) => {
    v[a] = v[a] + v[b] + x;
    v[d] = rotr(v[d] ^ v[a], 16);
    v[c] = v[c] + v[d];
    v[b] = rotr(v[b] ^ v[c], 12);
    v[a] = v[a] + v[b] + y;
    v[d] = rotr(v[d] ^ v[a], 8);
    v[c] = v[c] + v[d];
    v[b] = rotr(v[b] ^ v[c], 7);
  };

  blake2Blocks(bytes, 64, (block, offset, counter, last) => {
    for (let i = 0; i < 8; i++) {
      v[i] = h[i];
      v[i + 8] = BLAKE2S_IV[i];
    }
    v[12] ^= counter % TWO_POW_32;
    v[13] ^= Math.floor(counter / TWO_POW_32);
    if (last) {
      v[14] = ~v[14];
    }
    for (let i = 0; i < 16; i++) {
      m[i] = readUint32LE(block, offset + 4 * i);
    }
    for (let round = 0; round < 10; round++) {
      const s = BLAKE2_SIGMA[round];
      g(0, 4, 8, 12, m[s[0]], m[s[1]]);
      g(1, 5, 9, 13, m[s[2]], m[s[3]]);
      g(2, 6, 10, 14, m[s[4]], m[s[5]]);
      g(3, 7, 11, 15, m[s[6]], m[s[7]]);
      g(0, 5, 10, 15, m[s[8]], m[s[9]]);
      g(1, 6, 11, 12, m[s[10]], m[s[11]]);
      g(2, 7, 8, 13, m[s[12]], m[s[13]]);
      g(3, 4, 9, 14, m[s[14]], m[s[15]]);
    }
    for (let i = 0; i < 8; i++) {
      h[i] ^= v[i] ^ v[i + 8];
    }
  });
  return wordsToBytesLE(h, 32);
};

// ---------------------------------------------------------------------------
// HMAC (RFC 2104)
// ---------------------------------------------------------------------------

/**
 * HMAC over `hash` with the given block size in bytes: a key longer than the block is hashed
 * first, then zero-padded to the block size and combined with ipad (0x36) / opad (0x5c).
 */
export const hmac = (
  hash: (bytes: Uint8Array) => Uint8Array,
  blockSize: number,
  key: Uint8Array,
  message: Uint8Array
): Uint8Array => {
  const block = new Uint8Array(blockSize);
  block.set(key.length > blockSize ? hash(key) : key);
  const inner = new Uint8Array(blockSize + message.length);
  for (let i = 0; i < blockSize; i++) {
    inner[i] = block[i] ^ 0x36;
  }
  inner.set(message, blockSize);
  const innerDigest = hash(inner);
  const outer = new Uint8Array(blockSize + innerDigest.length);
  for (let i = 0; i < blockSize; i++) {
    outer[i] = block[i] ^ 0x5c;
  }
  outer.set(innerDigest, blockSize);
  return hash(outer);
};

/** HMAC-SHA3-256 with the block size 136 bytes (the SHA3-256 rate, as defined by NIST and used by OpenSSL). */
export const hmacSha3_256 = (key: Uint8Array, message: Uint8Array): Uint8Array =>
  hmac(sha3_256, SHA3_256_BLOCK_SIZE, key, message);

/** HMAC-SHA3-512 with the block size 72 bytes (the SHA3-512 rate, as defined by NIST and used by OpenSSL). */
export const hmacSha3_512 = (key: Uint8Array, message: Uint8Array): Uint8Array =>
  hmac(sha3_512, SHA3_512_BLOCK_SIZE, key, message);

// ---------------------------------------------------------------------------
// Checksums (error detection only)
// ---------------------------------------------------------------------------

/** The CRC-32 table for the reflected IEEE 802.3 polynomial 0xEDB88320, built once. */
const CRC32_TABLE = ((): Uint32Array => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  return table;
})();

/** CRC-32 (IEEE 802.3, as used by zip / gzip / PNG) as an unsigned 32-bit integer. */
export const crc32 = (bytes: Uint8Array): number => {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC32_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
};

/** The CRC-32C table for the reflected Castagnoli polynomial 0x82F63B78, built once. */
const CRC32C_TABLE = ((): Uint32Array => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0x82f63b78 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  return table;
})();

/** CRC-32C (Castagnoli, as used by iSCSI / SCTP / ext4) as an unsigned 32-bit integer. */
export const crc32c = (bytes: Uint8Array): number => {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC32C_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
};

/** The CRC-16 table for the polynomial 0x1021 (not reflected), built once. */
const CRC16_CCITT_TABLE = ((): Uint16Array => {
  const table = new Uint16Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n << 8;
    for (let k = 0; k < 8; k++) {
      c = c & 0x8000 ? ((c << 1) ^ 0x1021) & 0xffff : (c << 1) & 0xffff;
    }
    table[n] = c;
  }
  return table;
})();

/** CRC-16/CCITT-FALSE (polynomial 0x1021, initial value 0xFFFF, not reflected, no final XOR) as an unsigned 16-bit integer. */
export const crc16CcittFalse = (bytes: Uint8Array): number => {
  let crc = 0xffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = ((crc << 8) & 0xffff) ^ CRC16_CCITT_TABLE[((crc >>> 8) ^ bytes[i]) & 0xff];
  }
  return crc;
};

const ADLER32_MOD = 65521;
/** The largest n such that 255n(n+1)/2 + (n+1)(MOD-1) stays below 2^32 (as in zlib). */
const ADLER32_NMAX = 5552;

/** Adler-32 as an unsigned 32-bit integer. */
export const adler32 = (bytes: Uint8Array): number => {
  let a = 1;
  let b = 0;
  for (let offset = 0; offset < bytes.length; offset += ADLER32_NMAX) {
    const end = Math.min(offset + ADLER32_NMAX, bytes.length);
    for (let i = offset; i < end; i++) {
      a += bytes[i];
      b += a;
    }
    a %= ADLER32_MOD;
    b %= ADLER32_MOD;
  }
  return ((b << 16) | a) >>> 0;
};

/** FNV-1a 32-bit (offset basis 0x811c9dc5, prime 0x01000193) as an unsigned 32-bit integer. */
export const fnv1a32 = (bytes: Uint8Array): number => {
  let hash = 0x811c9dc5;
  for (let i = 0; i < bytes.length; i++) {
    hash = Math.imul(hash ^ bytes[i], 0x01000193);
  }
  return hash >>> 0;
};
