/** The input / output examples of the ENC table in docs/ROADMAP.md, as they are (⏎ = \n). */
export const ENC_ROADMAP_EXAMPLES: Record<string, { input: string; expected: string; shift?: number }> = {
  'ENC-001': { input: '<a href="x">', expected: '&lt;a href=&quot;x&quot;&gt;' },
  'ENC-002': { input: '&lt;b&gt; &#12354;', expected: '<b> あ' },
  'ENC-003': { input: 'aあ', expected: 'a&#12354;' },
  'ENC-004': { input: 'あ😀', expected: '\\u3042\\ud83d\\ude00' },
  'ENC-005': { input: '\\u3042', expected: 'あ' },
  'ENC-006': { input: '😀', expected: '\\u{1F600}' },
  'ENC-007': { input: 'foo?', expected: 'Zm9vPw' },
  'ENC-008': { input: 'Zm9vPw', expected: 'foo?' },
  'ENC-009': { input: 'foo', expected: 'MZXW6===' },
  'ENC-010': { input: 'MZXW6===', expected: 'foo' },
  'ENC-011': { input: 'hello', expected: 'Cn8eVZg' },
  'ENC-012': { input: 'Cn8eVZg', expected: 'hello' },
  'ENC-013': { input: 'abc', expected: '616263' },
  'ENC-014': { input: '61 62 63', expected: 'abc' },
  'ENC-015': { input: 'Hi', expected: '01001000 01101001' },
  'ENC-016': { input: '01001000 01101001', expected: 'Hi' },
  'ENC-017': { input: '例え.jp', expected: 'xn--r8jz45g.jp' },
  'ENC-018': { input: 'xn--r8jz45g.jp', expected: '例え.jp' },
  'ENC-019': { input: 'café', expected: 'caf=C3=A9' },
  'ENC-020': { input: 'caf=C3=A9', expected: 'café' },
  'ENC-021': { input: 'Hello', expected: 'Uryyb' },
  'ENC-022': { input: 'Hello', expected: 'w6==@' },
  'ENC-023': { input: 'abc', expected: 'def', shift: 3 },
  'ENC-024': { input: 'abc', expected: 'zyx' },
  'ENC-025': { input: 'hi', expected: '<~BP@~>' },
  'ENC-026': { input: '<~BP@~>', expected: 'hi' },
  'ENC-027': { input: 'hi', expected: 'H4sIAAAAAAAAE8vIBACsKpPYAgAAAA==' },
  'ENC-028': { input: 'H4sIAAAAAAAAE8vIBACsKpPYAgAAAA==', expected: 'hi' },
  'ENC-029': { input: 'a b&c', expected: 'a+b%26c' },
  'ENC-030': { input: 'a+b%26c', expected: 'a b&c' },
  'ENC-031': { input: 'a\nb', expected: 'YQ==\nYg==' },
  'ENC-032': { input: 'YQ==\nYg==', expected: 'a\nb' },
  'ENC-033': { input: 'ab1', expected: 'Alfa Bravo One' },
  'ENC-034': { input: 'hi', expected: 'data:text/plain;charset=utf-8;base64,aGk=' },
  'ENC-035': { input: '<a href="x">', expected: '&lt;a href=&quot;x&quot;&gt;' },
  'ENC-036': { input: '&lt;b&gt; &#12354;', expected: '<b> あ' },
  'ENC-037': { input: 'あ😀', expected: '\\u3042\\ud83d\\ude00' },
  'ENC-038': { input: '\\u3042', expected: 'あ' },
  'ENC-039': { input: 'abc', expected: '616263' },
  'ENC-040': { input: '61 62 63', expected: 'abc' },
};
